from helium import *
from time import *
start_chrome()
go_to("visualping.io")
input("Pls log in first:")
go_to("visualping.io/jobs")
sleep(8)
click("New Job")
sleep(5)
######Not_Done: type_in_url######
sleep(0.1)
click("Go")
sleep(0.1)
click("Tiny (1%)")
sleep(0.1)
click("Any change")
sleep(0.1)
click("Adjustments")
sleep(0.1)
click("None (Crawling from California US)")
sleep(0.1)
click("China")
sleep(0.1)
click("Area")
sleep(0.1)
click("All page")
sleep(0.1)
click("Double check before sending me an alert")
sleep(0.1)
click("Wait 2s")
sleep(0.1)
click("Wait 7s")
sleep(8)
click("创建工作")
sleep(0.1)
click("Create Job")
sleep(0.1)
click("Save")
